### ISSUE TITLE
RewritebleBatchedStatementsBasicDataSource is not abstract and does not override abstract method getParentLogger

### ISSUE THREAD

**Issue by nmusienko** [griddynamics/jagger#585]
[jagger:master]$ mvn clean install -e -X

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project chassis.core: Compilation failure
[ERROR] /Users/nikolay.musienko/dev/git/java/jagger/chassis/core/src/main/java/com/griddynamics/jagger/storage/rdb/RewritebleBatchedStatementsBasicDataSource.java:[11,7] error: RewritebleBatchedStatementsBasicDataSource is not abstract and does not override abstract method getParentLogger() in CommonDataSource
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project chassis.core: Compilation failure
/Users/nikolay.musienko/dev/git/java/jagger/chassis/core/src/main/java/com/griddynamics/jagger/storage/rdb/RewritebleBatchedStatementsBasicDataSource.java:[11,7] error: RewritebleBatchedStatementsBasicDataSource is not abstract and does not override abstract method getParentLogger() in CommonDataSource

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
/Users/nikolay.musienko/dev/git/java/jagger/chassis/core/src/main/java/com/griddynamics/jagger/storage/rdb/RewritebleBatchedStatementsBasicDataSource.java:[11,7] error: RewritebleBatchedStatementsBasicDataSource is not abstract and does not override abstract method getParentLogger() in CommonDataSource

	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more

**Comment by amikryukov** [comment]
Hi,
It's appears that this exception is not reproducible with **java 6**, but with **java 7** problem appears.
Here is small fix for java 7 : https://github.com/griddynamics/jagger/pull/587
