### ISSUE TITLE
Poor hadoop exceptions handling/logging

### ISSUE THREAD

**Issue by tanoshko** [griddynamics/jagger#843]
# Issue
Various issues connected with hadoop periodically occur, due to poor logging it is difficult to investigate what happened and if it is critical for the testing result.

Some issues are in master log in every run.

Error log messages from FSNamesystem and DFSClient 
12:32:52 ERROR 12:32:52,095  [Thread-0] FSNamesystem | FSNamesystem initialization failed.
12:32:52 org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /home/macys/runned_jagger/jaggerworkspace/master/storage/hdfs/namedir is in an inconsistent state: storage directory does not exist or is not accessible.
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:303)
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.loadFSImage(FSDirectory.java:100)
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.initialize(FSNamesystem.java:388)
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:362)
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:276)
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:496)
12:32:52 	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1279)
12:32:52 	at com.griddynamics.jagger.storage.fs.hdfs.HDFSNamenodeServer.start(HDFSNamenodeServer.java:44)
12:32:52 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:32:52 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:32:52 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:32:52 	at java.lang.reflect.Method.invoke(Method.java:497)
12:32:52 	at 
============================================

12:44:09 INFO 12:44:09,328  [Thread-0] Master | Report generated
12:44:09 INFO 12:44:09,345  [Thread-0] Master | Temporary data for session 24 deleted 
12:44:09 INFO 12:44:09,345  [Thread-0] JaggerXmlApplicationContext | Closing com.griddynamics.jagger.util.JaggerXmlApplicationContext@40d50c2b: startup date [Wed Dec 20 12:32:08 UTC 2017]; root of context hierarchy
12:44:09 INFO 12:44:09,352  [Thread-0] log | Stopped SelectChannelConnector@0.0.0.0:50070
12:44:09 INFO 12:44:09,476  [Thread-0] log | Stopped SelectChannelConnector@0.0.0.0:50075
12:44:10 ERROR 12:44:10,585  [Thread-0] DFSClient | Exception closing file /user/macys/24/task-2/DURATION/aggregated.dat : java.io.IOException: Call to nfr-customer-jagger.c.ace-tranquility-749.internal/172.17.1.235:8020 failed on local exception: java.io.EOFException
12:44:10 java.io.IOException: Call to nfr-customer-jagger.c.ace-tranquility-749.internal/172.17.1.235:8020 failed on local exception: java.io.EOFException
12:44:10 	at org.apache.hadoop.ipc.Client.wrapException(Client.java:1107)
12:44:10 	at org.apache.hadoop.ipc.Client.call(Client.java:1075)
12:44:10 	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
12:44:10 	at com.sun.proxy.$Proxy36.complete(Unknown Source)
12:44:10 	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
12:44:10 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:44:10 	at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by tanoshko** [comment]
[jagger_master.log](https://github.com/griddynamics/jagger/files/1591662/jagger_master.log)
Attaching master log with java.io.EOFException at 15:12:10,683

**Comment by tanoshko** [comment]
[jagger_master.log](https://github.com/griddynamics/jagger/files/1591662/jagger_master.log)
Attaching master log with java.io.EOFException at 15:12:10,683

newer one [jagger_eof.log](https://github.com/griddynamics/jagger/files/1603235/jagger_eof.log)

Configuration: 2 kernels, jagger properties file below
[zeus.environment_sharable.properties.txt](https://github.com/griddynamics/jagger/files/1603240/zeus.environment_sharable.properties.txt)
