### ISSUE TITLE
Test with 1 invocation fails

### ISSUE THREAD

**Issue by tanoshko** [griddynamics/jagger#844]
# Issue

if test contains of one invocation. While it is considered as a valid test case if we need to monitor performance of some long running job.

JLoadProfile loadProfile = JLoadProfileInvocation.builder(InvocationCount.of(1), ThreadCount.of(1)).build();
JTerminationCriteria terminationCriteria = JTerminationCriteriaIterations.of(IterationsNumber.of(1), MaxDurationInSeconds.of(60));

Jagger fails with exception:  JDBCExceptionReporter | 'Infinity' is not a valid numeric or approximate numeric value

In single and distributed mode we get:

ERROR 17:13:54,842 [jagger-core-pool-3] JDBCExceptionReporter | 'Infinity' is not a valid numeric or approximate numeric value
ERROR 17:13:54,883 [jagger-core-pool-3] Master | Error during log processing
org.springframework.dao.TransientDataAccessResourceException: Hibernate operation: could not insert: [com.griddynamics.jagger.dbapi.entity.MetricSummaryEntity]; SQL [insert into MetricSummaryEntity (metricDescription_id, total) values (?, ?)]; 'Infinity' is not a valid numeric or approximate numeric value; nested exception is java.sql.SQLException: 'Infinity' is not a valid numeric or approximate numeric value

**Comment by Amacuse** [comment]
If we set up:

JLoadProfile loadProfile = JLoadProfileInvocation.builder(InvocationCount.of(1), ThreadCount.of(1)).build();
JTerminationCriteria terminationCriteria = JTerminationCriteriaIterations.of(IterationsNumber.of(1), MaxDurationInSeconds.of(60));

In single and distributed mode we get:

ERROR 17:13:54,842  [jagger-core-pool-3] JDBCExceptionReporter | 'Infinity' is not a valid numeric or approximate numeric value
ERROR 17:13:54,883  [jagger-core-pool-3] Master | Error during log processing
org.springframework.dao.TransientDataAccessResourceException: Hibernate operation: could not insert: [com.griddynamics.jagger.dbapi.entity.MetricSummaryEntity]; SQL [insert into MetricSummaryEntity (metricDescription_id, total) values (?, ?)]; 'Infinity' is not a valid numeric or approximate numeric value; nested exception is java.sql.SQLException: 'Infinity' is not a valid numeric or approximate numeric value
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:108)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertJdbcAccessException(HibernateAccessor.java:428)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:414)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:416)
	at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:379)
	at org.springframework.orm.hibernate3.HibernateTemplate.persist(HibernateTemplate.java:834)
	at com.griddynamics.jagger.storage.fs.logging.LogProcessor.persistAggregatedMetricValue(LogProcessor.java:52)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor.access$800(DurationLogProcessor.java:70)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor$StatisticsGenerator.generate(DurationLogProcessor.java:261)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor.processLog(DurationLogProcessor.java:160)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor.onTaskDistributionCompleted(DurationLogProcessor.java:134)
	at com.griddynamics.jagger.master.CompositeDistributionListener.onTaskDistributionCompleted(CompositeDistributionListener.java:54)
	at com.griddynamics.jagger.master.ListenableService$3$1.run(ListenableService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: 'Infinity' is not a valid numeric or approximate numeric value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:929)
	at com.mysql.jdbc.PreparedStatement.setDouble(PreparedStatement.java:3637)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setDouble(DelegatingPreparedStatement.java:126)
	at org.hibernate.type.descriptor.sql.DoubleTypeDescriptor$1.doBind(DoubleTypeDescriptor.java:52)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:91)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:283)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:278)
	at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:89)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2184)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2161)
	at org.hibernate.persister.entity.AbstractEntityPersister$4.bindValues(AbstractEntityPersister.java:2339)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:55)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2346)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2853)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:265)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.springframework.orm.hibernate3.HibernateAccessor.flushIfNecessary(HibernateAccessor.java:394)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:412)

**Comment by Amacuse** [comment]
More details for reproducing:

1. Take the Jagger test example from a class com.macys.platform.ExampleSimpleJLoadScenarioProvider 

1. Change these two lines of code:
JLoadProfile jLoadProfileRps = JLoadProfileRps.builder(RequestsPerSecond.of(10)).withMaxLoadThreads(10).withWarmUpTimeInMilliseconds(10000).build();
JTerminationCriteria jTerminationCriteria = JTerminationCriteriaIterations.of(IterationsNumber.of(500), MaxDurationInSeconds.of(30));

to

JLoadProfile jLoadProfileRps = JLoadProfileInvocation.builder(InvocationCount.of(**1**), ThreadCount.of(**1**)).build();
JTerminationCriteria jTerminationCriteria = JTerminationCriteriaIterations.of(IterationsNumber.of(**1**), MaxDurationInSeconds.of(30));

3. Launch 'ls_example' test in distributed or local mode

Log is attached
[jagger_agent.log](https://github.com/griddynamics/jagger/files/1587114/jagger_agent.log)

**Comment by dlatnikov** [comment]
done in 2.0.1-m2

**Comment by Amacuse** [comment]
Hi, I downloaded the latest jagger version and tested it. I took the same example which is described above. SQL exception is really gone, but all metrics have gone too. In Summary&Trends on UI I can see Throughput, Latency etc., but in Metrics I see only 'Virtual users'.
Could you clarify this behavior? Is it expected?
P.S. In jagger version 1.2.5 all metrics was available in such JLoadProfile configuration and was represented as one dot on the plot.
Thank you in advance.
