### ISSUE TITLE
exception occurs at attempt to execute test with '1 thread 1 invocation' JLoadProfile

### ISSUE THREAD

**Issue by ctpe71ok** [griddynamics/jagger#855]
Exception occurs at attempt to execute test with '1 thread 1 invocation' JLoadProfile

execute test with

        JLoadProfile oneInvocation = JLoadProfileInvocation
                .builder(
                        InvocationCount.of(1),
                        ThreadCount.of(1))
                .build();

        JLimit successRateLimit = JLimitVsRefValue.builder(JMetricName.PERF_SUCCESS_RATE_OK, RefValue.of(1D))
                .withOnlyWarnings(LowWarnThresh.of(0.99), UpWarnThresh.of(1.01))
                .build();

        JLimit throughputLimit = JLimitVsBaseline.builder(JMetricName.PERF_THROUGHPUT)
                // the threshold is relative.
                .withOnlyErrors(LowErrThresh.of(0.99), UpErrThresh.of(1.00001))
                .build();

        JLimit latencyPercentileLimit = JLimitVsRefValue.builder(JMetricName.PERF_LATENCY_PERCENTILE(95D), RefValue.of(0.1D))
                // the threshold is relative.
                .withOnlyWarnings(LowWarnThresh.of(0.50), UpWarnThresh.of(1.5))
                .build();

        JLoadTest jLoadTest = JLoadTest
                .builder(Id.of("test"), jTestDefinition, oneInvocation, jTerminationCriteriaDuration)
                .addListener(new CollectThreadsTestListener())
                .withLimits(successRateLimit)
                .withLimits(successRateLimit, throughputLimit, latencyPercentileLimit)
                .build();

Please find exception below

With JLoadProfile 2 invocations with one thread - works ok.

        JLoadProfile twoInvocations = JLoadProfileInvocation
                .builder(
                        InvocationCount.of(2),
                        ThreadCount.of(1))
                .build();

WARN 15:19:34,218  [jagger-core-pool-4] JDBCExceptionReporter | SQL Error: 0, SQLState: S1009
ERROR 15:19:34,219  [jagger-core-pool-4] JDBCExceptionReporter | 'Infinity' is not a valid numeric or approximate numeric value
ERROR 15:19:34,288  [jagger-core-pool-4] Master | Error during log processing
org.springframework.dao.TransientDataAccessResourceException: Hibernate operation: could not insert: [com.griddynamics.jagger.dbapi.entity.MetricSummaryEntity]; SQL [insert into MetricSummaryEntity (metricDescription_id, total) values (?, ?)]; 'Infinity' is not a valid numeric or approximate numeric value; nested exception is java.sql.SQLException: 'Infinity' is not a valid numeric or approximate numeric value
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:108)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertJdbcAccessException(HibernateAccessor.java:428)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:414)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:416)
	at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:379)
	at org.springframework.orm.hibernate3.HibernateTemplate.persist(HibernateTemplate.java:834)
	at com.griddynamics.jagger.storage.fs.logging.LogProcessor.persistAggregatedMetricValue(LogProcessor.java:52)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor.access$800(DurationLogProcessor.java:70)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor$StatisticsGenerator.generate(DurationLogProcessor.java:261)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor.processLog(DurationLogProcessor.java:160)
	at com.griddynamics.jagger.engine.e1.aggregator.workload.DurationLogProcessor.onTaskDistributionCompleted(DurationLogProcessor.java:134)
	at com.griddynamics.jagger.master.CompositeDistributionListener.onTaskDistributionCompleted(CompositeDistributionListener.java:54)
	at com.griddynamics.jagger.master.ListenableService$3$1.run(ListenableService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: 'Infinity' is not a valid numeric or approximate numeric value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1075)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:929)
	at com.mysql.jdbc.PreparedStatement.setDouble(PreparedStatement.java:3637)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setDouble(DelegatingPreparedStatement.java:126)
	at org.hibernate.type.descriptor.sql.DoubleTypeDescriptor$1.doBind(DoubleTypeDescriptor.java:52)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:91)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:283)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:278)
	at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:89)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2184)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2161)
	at org.hibernate.persister.entity.AbstractEntityPersister$4.bindValues(AbstractEntityPersister.java:2339)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:55)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2346)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2853)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:265)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.springframework.orm.hibernate3.HibernateAccessor.flushIfNecessary(HibernateAccessor.java:394)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:412)
	... 12 more

**Comment by dlatnikov** [comment]
duplicates https://github.com/griddynamics/jagger/issues/844. Should be fixed in master branch now
